### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by iRayanKhan** [Supereg/secure-video-specification#1]
Hi there,
I don't mean to be a bother, but I am intrigued by this project.
Is there anything that I can aid with or try to help with to complete the circuit and have this added into HomeKit? If not, what is there left to do?

**Comment by bauer-andreas** [comment]
Probably everything about the current milestones can be found here: https://github.com/KhaosT/HAP-NodeJS/issues/741#issuecomment-584901408

**Comment by iRayanKhan** [comment]
Thank you, I appreciate the work and insight.
