### ISSUE TITLE
packet spec seems to have conflicting information

### ISSUE THREAD

**Issue by koush** [Supereg/secure-video-specification#5]
I'm having some trouble to get HomeKit to accept the mock files that you have in your examples. I did notice there seemed to be conflicting information about the dataSend data event construction:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/73924/130143134-ebaaf05f-bab3-427a-9b3f-7285f80697c8.png">

The spec indicates that "packets" is an array, but then following examples show it as a dictionary:

```json
{
  "header": {
    "protocol": "dataSend",
    "event": "data"
  },
  "message": {
    "streamId": 1,
    "packets": {
      "metadata": {
        "dataType": "mediaInitialization",
        "dataSequenceNumber": 1,
        "isLastDataChunk": true,
        "dataChunkSequenceNumber": 1
      },
      "data": "contents of ./chunks/mediaInitialization.mp4"
    }
  } 
}
```

So I think it should be this according to your written spec:

```json

{
  "header": {
    "protocol": "dataSend",
    "event": "data"
  },
  "message": {
    "streamId": 1,
    "packets": [
      {
        "metadata": {
          "dataType": "mediaInitialization",
          "dataSequenceNumber": 1,
          "isLastDataChunk": true,
          "dataChunkSequenceNumber": 1
        },
        "data": "contents of ./chunks/mediaInitialization.mp4"
      }
    ]
  } 
}

```

**Comment by koush** [comment]
Somewhat related question, how is the data binary blob encoded? Right now, I'm just passing it to HAP-NodeJS as a Buffer, and it presumably handles it correctly, but I am unsure.

**Comment by koush** [comment]
Have confirmed that the examples are incorrect, because after correcting, everything works. HSV support in HAP-NodeJS!

**Comment by bauer-andreas** [comment]
Here is a full example of a communication that worked for me https://github.com/Supereg/secure-video-specification/tree/master/examples
Those are incorrect?

**Comment by bauer-andreas** [comment]
The "**array** of dictionaries" comes from the public spec.
The `dataSend` `data` event is not special to HKSV but a generalized way of sending data through the HK Data Stream.
It is e.g. also used for voice data transmission for the Siri functionality of HomeKit Apple TV Remotes. And there you would actually send an array of packets.

But good to know, that they **force** a plain dictionary for HKSV.

I'll edit the spec.

**Comment by bauer-andreas** [comment]
Okay, wait a sec, what is now expected from homed, an array of length 1 or a dictionary?

**Comment by koush** [comment]
> Okay, wait a sec, what is now expected from homed, an array of length 1 or a dictionary?

Currently, my implementation is working with an array of packets length 1. I will double check with a dictionary and get back to you. Maybe a dictionary works too?

**Comment by koush** [comment]
I can confirm that a dictionary does not work, at least using HAP-NodeJS to encode the payload.

I believe the spec samples are incorrect here.
