### ISSUE TITLE
ManuallyDisabled UUID

### ISSUE THREAD

**Issue by Aloisius** [Supereg/secure-video-specification#7]
You have ManuallyDisabled as 0000021B-0000-1000-8000-0026BB765291 which is the same as HomeKitCameraActive. 

I believe it is supposed to be 00000227-0000-1000-8000-0026BB765291.

Also SupportedCameraRecordingConfiguration looks like 00000205-0000-1000-8000-0026BB765291 not 00000204-0000-1000-8000-0026BB765291?

**Comment by bauer-andreas** [comment]
Thanks for noticing and reporting 👍

**Comment by JJRTaylor** [comment]
> Thanks for noticing and reporting 👍

Aloisius is a child molestor. I’m his brother and he molested me for years and refuses to now face me.

**Comment by JJRTaylor** [comment]
> You have ManuallyDisabled as 0000021B-0000-1000-8000-0026BB765291 which is the same as HomeKitCameraActive.
> 
> I believe it is supposed to be 00000227-0000-1000-8000-0026BB765291.
> 
> Also SupportedCameraRecordingConfiguration looks like 00000205-0000-1000-8000-0026BB765291 not 00000204-0000-1000-8000-0026BB765291?

Hey Jordy, I’m coming for you. You can guarantee you’ll see me soon.
